<div class="container">
    <div class="box_center box_rebueno_information">
        <h2>Contáctanos</h2>
        <hr class="medium">
        <section>
            <p>Si tienes alguna duda sobre <b><?php echo $empresa['nombre'];?> </b> puedes contactarnos: llamándonos al <?php echo $empresa['telefono'];?> o escribiéndonos a los correos electrónicos de contacto:</p>
            <p>Si eres Cliente de <?php echo $empresa['nombre'];?> escríbenos a <a href="mailto:clientes@<?php echo $empresa['dominio'];?>" title="clientes@<?php echo $empresa['dominio'];?>">clientes@<?php echo $empresa['dominio'];?></a>.</p>
            <p>Si eres Socio (o quieres serlo) escríbenos a <a href="mailto:socios@<?php echo $empresa['dominio'];?>" title="socios@<?php echo $empresa['dominio'];?>">socios@<?php echo $empresa['dominio'];?></a>.</p>
        </section>
    </div>
</div>