<?php
/*******************
 * 1 Normal - Rebueno
 * 2 Excursion
 * 3 Paquetes
 */
$tipo_pantalla = 1;


if (! function_exists('array_column')) {
    function array_column(array $input, $columnKey, $indexKey = null) {
        $array = array();
        foreach ($input as $value) {
            if ( ! isset($value[$columnKey])) {
                trigger_error("Key \"$columnKey\" does not exist in array");
                return false;
            }
            if (is_null($indexKey)) {
                $array[] = $value[$columnKey];
            }
            else {
                if ( ! isset($value[$indexKey])) {
                    trigger_error("Key \"$indexKey\" does not exist in array");
                    return false;
                }
                if ( ! is_scalar($value[$indexKey])) {
                    trigger_error("Key \"$indexKey\" does not contain scalar value");
                    return false;
                }
                $array[$value[$indexKey]] = $value[$columnKey];
            }
        }
        return $array;
    }
}

function crearUrl($str_cadena) {
    $nueva_cadena = trim($str_cadena);
    $nueva_cadena = str_replace('-', ' ', $nueva_cadena);
    $nueva_cadena = str_replace(' ', '-', $nueva_cadena);
    $nueva_cadena = str_replace(chr(47), '-', $nueva_cadena);
    $nueva_cadena = str_replace(chr(63), '', $nueva_cadena);
    return $nueva_cadena;
}

$maximo_cupones = 0;
$vendidos = 0;
foreach ($data_v as $vendidos) {
    $maximo_cupones = $vendidos['maximo_cupones'];
    $vendidos = $vendidos['vendidos'];
}
?>
<div  class="container">
<?php

foreach ($data as $detalle) {
    $fecha_final = $detalle['fecha_final'];
    $tipo_pantalla = $detalle['id_tipo_pantalla'];
    ?>
    <div style="display:inline-block;width:100%">
        <div class="detalle-titulo"><p><?php echo $detalle['titulo']; ?></p></div>
        <?php if($tipo_pantalla == 1) { ?>
        <div id="carousel-detalle-promocion" class="carousel slide carrusel-detalle" data-ride="carousel">
        <?php } else { ?>
        <div id="carousel-detalle-promocion" class="carousel slide carrusel-detalle-total" data-ride="carousel">
        <?php } ?>
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <?php
                if (file_exists($directorio.$detalle['id_campana'].$sep_path .'small')){
                    $ficheros = scandir($directorio.$detalle['id_campana'].$sep_path .'small');
                    $contador = -1;
                    foreach ($ficheros as $file) {
                        if ($file == '.' || $file == '..')
                            continue;
                        $contador++;
                        ?>
                        <li data-target="#carousel-detalle-promocion" data-slide-to="<?php echo $contador; ?>" <?php if ($contador == 0) { ?> class="active" <?php } ?>></li>
                        <?php
                    }
                }
                ?>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php
                $contador = -1;
                if(count($ficheros) > 0) {
                    foreach ($ficheros as $file) {
                        if ($file == '.' || $file == '..')
                            continue;
                        $contador++;

                        $ruta_imagen_pro = $directorio.$detalle['id_campana'].$sep_path .'small'.$sep_path.$file;
                        if (file_exists($ruta_imagen_pro)){
                            ob_start();
                            $resource_image = imagecreatefromjpeg($ruta_imagen_pro);
                            imagejpeg($resource_image);
                            $imagedata = ob_get_clean();
                            $image = 'data:image/jpeg;base64,'.base64_encode($imagedata);
                        } else {
                            $image = '';
                        }

                        ?>
                        <div class="item<?php if ($contador == 0) { ?>  active<?php } ?>">
                            <div class="slider-detalle">
                                <img src="<?php echo $image; ?>">
                            </div>
                            <div class="carousel-caption"></div>
                        </div>
                        <?php
                    }
                }
                ?>
            </div>
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-detalle-promocion" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-detalle-promocion" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>

        <?php
        $cantidad = 0;
        $cantidad_opcion = 0;
        $cantidad_seleccion = 0;
        $total = count($data_o);
        $opciones_saber = array();
        $id_opcion_anterior = -1;
        $inicio_opcion_seleccion_left = 0;
        $inicio_opcion_seleccion_right = 0;
        foreach ($data_o as $opciones) {
            $id_opcion = $opciones['id_campana_opcion'];
            $cantidad++;
            if($id_opcion != $id_opcion_anterior) {
                $cantidad_opcion++;
                $cantidad_seleccion = 0;
            }
            $mostrar_opciones = true;
            if ($cantidad == 1) {
                ?>
                <?php if($tipo_pantalla == 1) { ?>
                <div class="contenedor-compra-detalle" id="detalle_precio"> 
                    <div class="box_center_d">
                        <span class="text">Precio <?php echo $moneda['simbolo'];?></span>
                        <span class="priceBuy"><?php echo $opciones['precio_especial']; ?></span>
                    </div>
                    <?php
                        if( $maximo_cupones > 0 ) { 
                                    $quedan = $maximo_cupones - $vendidos;
                                    if( $quedan <= 10 ) { 
                                        if( $quedan <= 0 ) { ?>
                                            <button type="button" class="btn btn_buy_action disabled" data-toggle="modal" data-target="#exampleModal" >Comprar</button>
                                  <?php } else { 
                                            if ($total == 1) { ?>
                                           <a href="../../campana/formulariopago/<?php echo base64_encode($opciones['id_campana']); ?>/<?php echo base64_encode($opciones['id_campana_opcion']); ?>" title="Comprar" class="btn btn_buy_action">Comprar</a>
                                       <?php } else { ?> 
                                           <button type="button" class="btn btn_buy_action" data-toggle="modal" data-target="#exampleModal" >Comprar</button>
                                       <?php }
                                        }
                                    } else {
                                        if ($total == 1) { ?>
                                            <a href="../../campana/formulariopago/<?php echo base64_encode($opciones['id_campana']); ?>/<?php echo base64_encode($opciones['id_campana_opcion']); ?>" title="Comprar" class="btn btn_buy_action">Comprar</a>
                                        <?php } else { ?> 
                                            <button type="button" class="btn btn_buy_action" data-toggle="modal" data-target="#exampleModal" >Comprar</button>
                                        <?php } 
                                    }
                        } else {
                            if ($total == 1) { ?>
                               <a href="../../campana/formulariopago/<?php echo base64_encode($opciones['id_campana']); ?>/<?php echo base64_encode($opciones['id_campana_opcion']); ?>" title="Comprar" class="btn btn_buy_action">Comprar</a>
                           <?php } else { ?> 
                               <button type="button" class="btn btn_buy_action" data-toggle="modal" data-target="#exampleModal" >Comprar</button>
                           <?php } 
                        } 
                    ?>
                    <ul class="discount_information">
                        <li><span>Precio Regular</span>
                            <div class="value">
                                <s><?php echo $moneda['simbolo'];?><?php echo $opciones['precio_regular']; ?></s>
                            </div>
                        </li>
                        <li><span>Descuento</span>
                            <div class="value"><?php echo $opciones['descuento']; ?>%</div>
                        </li>
                        <li><span>Ahorro</span>
                            <div class="value"><?php echo $moneda['simbolo'];?><?php echo $opciones['ahorro']; ?></div>
                        </li>
                    </ul>
                    <?php if($tipo_pantalla == 1) { ?>
                    <p class="sold_campaignsp">Se han vendido <b><?php echo $opciones['vendidos']; ?> </b>ofertas</p>
                    <?php } ?>
                    <div class="time_campaigns">
                        <div class="name">La oferta finaliza en</div>
                        <div class="result"><i class="fa fa-clock-o"></i>&nbsp;&nbsp;&nbsp;<span id='cntdwn'></span></div>
                    </div>
                    <div data-title="<?php echo $detalle['titulo']; ?>" data-email="<?php echo $localhost;?>/campana/detalle/<?php echo crearUrl($detalle['subtitulo']).'--'.base64_encode($detalle['id_campana']); ?>.html">
                        <ul class="share_buttons" >
                            <li><span >Comparte:</span></li>
                            <li><a href="javascript:shareFacebook();" title="Comparte en Facebook" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a target="_blank" title="Comparte en Twitter" class="btn btn-social-icon btn-twitter"><i class="fa fa-twitter"></i></a></li>
                            <!--li><a href="javascript:;" title="Comparte en Google+" class="btn btn-social-icon btn-google-plus"><i class="fa fa-google-plus"></i>></a></li>
                            <li><a href="javascript:;" title="Comparte por email" class="mail addthis_button_email"></a></li-->
                        </ul>
                    </div>                
                </div>
                <?php } else { ?>
                <div class="contenedor-compra-detalle total" id="detalle_precio"> 
                    <div class="value super-tachado">
                        <s><?php echo $moneda['simbolo'];?><?php echo $opciones['precio_regular']; ?></s>
                    </div>
                    <div class="value">
                        <div class="value super-notachado left">Precio : </div><div class="value super-notachado right"><s><?php echo $moneda['simbolo'];?><?php echo $opciones['precio_especial']; ?></s></div>
                    </div>
                    <div class="value">
                        <a data-opcion="1" href="#tabempresa" title="Reservar" class="btn btn_buy_action total excursion">RESERVAR <span class="glyphicon glyphicon-play"></span></a>
                    </div>
                </div>
                <?php } ?>
                <div class="modal fade" id="exampleModal" tabindex="100" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="exampleModalLabel">Elija su promoción</h4>
                            </div>
                            <div class="modal-body">
                               <?php
                                $opciones_saber[] = $opciones['descripcion'];
                                }
                                
                                $opcion_venta_ant = "<div class='form-group'>";
                                $opcion_venta_ant.= "<label for='message-text' class='col-lg-9 control-label'>";
                                $opcion_venta_ant.= "<span class='text-opcion'>OPCIÓN ".$cantidad." :</span>";
                                $opcion_venta_ant.= " <b>".$opciones['descripcion']."</b>";
                                $opcion_venta_ant.= "<span class='text-precio'>Precio Regular : ".$moneda['simbolo']." ".$opciones['precio_regular'];
                                $opcion_venta_ant.= " - Descuento : ".$opciones['descuento'];
                                $opcion_venta_ant.= " % - Ahorra : ".$moneda['simbolo']." ".$opciones['ahorro']."</span></label>";
                                $opcion_venta_ant.= "<a href='../../campana/formulariopago/".base64_encode($opciones['id_campana'])."/".base64_encode($opciones['id_campana_opcion'])."' ";
                                $opcion_venta_ant.= "title='Comprar' class='btn btn_buy_action_opcion btn-sm'>";
                                $opcion_venta_ant.= $moneda['simbolo']." ".$opciones['precio_especial']."</a>";
                                $opcion_venta_ant.= "</div>";
                                
                                if($tipo_pantalla == 3) {
                                    $opcion_venta_total = $opcion_venta."<div class='opcion-venta-excursion grupo-paquete-top'>";
                                    $opcion_venta_total.= $opcion_seleccion_top;
                                    $opcion_venta_total.= "</div>";
                                    $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-left'>";
                                    $opcion_venta_total.= "<div class='opcion-seleccion-row titulo-left'>Estandar</div>";
                                    $opcion_venta_total.= $opcion_seleccion_left;
                                    $opcion_venta_total.= "<div class='opcion-seleccion-row pie-left'>Seleccionar Hotel prioridad</div>";
                                    $opcion_venta_total.= "</div>";
                                    $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-right'>";
                                    $opcion_venta_total.= $opcion_seleccion_right;
                                    $opcion_venta_total.= "<div class='opcion-seleccion-row pie-right'>En caso de no contar con disponibilidad se acomodara al pax en similar o superior</div>";
                                    $opcion_venta_total.= "</div>".$opcion_venta_bottom;
                                } else {
                                    $opcion_venta_total = $opcion_venta."<div class='opcion-venta-excursion grupo-seleccion-left'>".$opcion_seleccion_left."</div><div class='opcion-venta-excursion grupo-seleccion-right'>".$opcion_seleccion_right."</div>".$opcion_venta_bottom;
                                }
                                                                
                                if($id_opcion_anterior != $id_opcion && $id_opcion_anterior != -1 ) {
                                    $venta_opciones[] = array('id'   => $id_opcion_anterior,
                                                              'form' => $opcion_venta_total);
                                    
                                    ?>
                                    <div class="modal-content">
                                        <form class="form-horizontal" role="form">
                                            <?php echo $opcion_venta_ant;?>
                                        </form>
                                    </div>
                                    <?php
                                    $opcion_seleccion_left = "";
                                    $opcion_seleccion_right = "";
                                    $opcion_seleccion_top = "";
                                }
                                
                                
                                
                                $opcion_venta = "<div class='opcion-venta-excursion'>";
                                $opcion_venta.= "<div class='opcion-venta-excursion opcion-seleccion'>";
                                //$opcion_venta.= "<div boton-seleccion='".$opciones['id_campana_opcion']."' class='btn btn_buy_action_opcion btn-sm'>comprar</div>";
                                $opcion_venta.= "<input type='hidden' id='total-opcion".$opciones['id_campana_opcion']."' name='total-opcion".$opciones['id_campana_opcion']."' value='0'>";
                                /*$opcion_venta.= "<label for='message-text' class='col-lg-9 control-label'>";
                                $opcion_venta.= "<span class='text-opcion'>OPCIÓN ".$cantidad_opcion." :</span>";
                                $opcion_venta.= " <b>".$opciones['descripcion']."</b>";
                                $opcion_venta.= "<span class='text-precio'>Precio Regular : ".$moneda['simbolo']." ".$opciones['precio_regular'];
                                $opcion_venta.= " - Descuento : ".$opciones['descuento'];
                                $opcion_venta.= " % - Ahorra : ".$moneda['simbolo']." ".$opciones['ahorro']."</span></label>";*/
                                if($tipo_pantalla == 2) {
                                    $opcion_venta.= "<div class='opcion-venta-excursion opcion-venta'>";
                                    $opcion_venta.= "<div class='opcion-venta-excursion titulo-excursion'>Seleccionar fecha y Cantidad de pax</div>";
                                    $duracion = "";
                                    if(!empty($detalle['duracion_dias'])) $duracion .= $detalle['duracion_dias']." días ";
                                    if(!empty($detalle['duracion_noches'])) $duracion .= $detalle['duracion_noches']." noches ";
                                    if(!empty($detalle['duracion_horas'])) $duracion .= $detalle['duracion_horas']." horas";
                                    if(!empty($duracion)) {
                                        $opcion_venta.= "<div class='opcion-venta-excursion titulo-duracion'><span class='glyphicon glyphicon-time'></span> Duración ".$duracion."</div>";
                                    }
                                    if(!empty($detalle['duracion_observacion'])) {
                                        $opcion_venta.= "<div class='opcion-venta-excursion titulo-observacion'>".$detalle['duracion_observacion']."</div>";
                                    }
                                    $opcion_venta.= "</div>";
                                }
                                
                                $opcion_venta.= "<div class='opcion-venta-excursion opcion-venta'>";
                                
                                $opcion_venta_bottom = "</div>";
                                $opcion_venta_bottom.= "</div>";
                                $opcion_venta_bottom.= "<div class='opcion-venta-excursion opcion-boton'>";
                                $opcion_venta_bottom.= "<div class='boton-venta'><a id='btntotal-opcion".$opciones['id_campana_opcion']."' boton-precio='form-opcion-venta".$opciones['id_campana_opcion']."' campana='".base64_encode($opciones['id_campana'])."' ";
                                $opcion_venta_bottom.= "campana-opcion='".base64_encode($opciones['id_campana_opcion'])."' title='Comprar' class='btn btn_buy_action_opcion btn-sm'>";
                                $opcion_venta_bottom.= "<div style='font-size:13px'>Precio</div>";
                                if( !empty($opciones['id_opcion_seleccion']) ) {
                                    if($cantidad_seleccion > 0) {
                                        $opcion_venta_bottom.= $moneda['simbolo']." 0.00</a></div>";
                                    } else {
                                        $opcion_venta_bottom.= $moneda['simbolo']." ".$opciones['precio_especial']."</a></div>";
                                    }
                                } else {
                                    $opcion_venta_bottom.= $moneda['simbolo']." ".$opciones['precio_especial']."</a></div>";
                                }
                                
                                $opcion_venta_bottom.= "<div class='boton-venta'><a id='btncomprar-opcion".$opciones['id_campana_opcion']."' boton-reserva='form-opcion-venta".$opciones['id_campana_opcion']."' campana='".base64_encode($opciones['id_campana'])."' ";
                                $opcion_venta_bottom.= "campana-opcion='".base64_encode($opciones['id_campana_opcion'])."' title='Comprar' class='btn btn_buy_action_opcion btn-sm' href='/campana/completardatos' ";
                                if(count($carrito_session) == 0) $opcion_venta_bottom.= "disabled='disabled'";
                                $opcion_venta_bottom.= "><div style='font-size:13px'>COMPRAR  <span class='glyphicon glyphicon-play'></span></div></a></div>";
                                
                                $opcion_venta_bottom.= "<div class='boton-venta'><a id='btncarrito-opcion".$opciones['id_campana_opcion']."' boton-carrito='form-opcion-venta".$opciones['id_campana_opcion']."' campana='".base64_encode($opciones['id_campana'])."' ";
                                $opcion_venta_bottom.= "campana-opcion='".base64_encode($opciones['id_campana_opcion'])."' title='Comprar' class='btn btn_buy_action_opcion btn-sm' disabled='disabled'>";
                                $opcion_venta_bottom.= "<div style='font-size:13px'><span class='badge' id='opcion-cantidad-carrito'>".count($carrito_session)."</span>  AGREGAR  <span class='glyphicon glyphicon-shopping-cart'></span></div></a></div>";
                                
                                $opcion_venta_bottom.= "</div>";
                                $opcion_venta_bottom.= "</div>";
                                
                                $tipo_seleccion      = $opciones['tipo_seleccion']; 
                                $cabecera_seleccion  = $opciones['cabecera_precio']; 
                                $mostrar_detalle     = $opciones['mostrar_detalle'];
                                $dias_bloqueo        = $opciones['dias_bloqueo']; 
                                $valori              = $opciones['valor_inicial']; 
                                $valorf              = $opciones['valor_final'];
                                $incremento          = $opciones['incremento'];
                                $utiliza_descripcion = $opciones['utiliza_descripcion_precio'];
                                $importe             = $opciones['importe_seleccion'];
                                $descripcion         = $opciones['descripcion_interna'];
                                
                                if( !empty($opciones['id_opcion_seleccion']) ) {
                                
                                    $opcion_seleccion = "<div class='form-group opcion-seleccion'>";
                                    $es_extendido = false;
                                    if(empty($cabecera_seleccion) && empty($mostrar_detalle)) {
                                        $opcion_seleccion.= "<label for='categoria' class='col-lg-5 control-label'><b>".$opciones['descripcion_primaria']."</b> ".$opciones['descripcion_secundaria']." :</label>";
                                    }
                                    $opcion_seleccion.= "<input type='hidden' id='precio-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='precio-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='label-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='label-opcion-seleccion[]' value='<b>".$opciones['descripcion_primaria']."</b> ".$opciones['descripcion_secundaria']."'>";
                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='cantidad-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='keyseleccion-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='keyseleccion-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='total-adultos-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='total-adultos-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='total-ninos-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='total-ninos-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='total-infantes-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='total-infantes-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-ninos-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='cantidad-ninos-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-infantes-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='cantidad-infantes-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='label-habitacion-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='label-habitacion-opcion-seleccion[]' value=''>";
                                    $opcion_seleccion.= "<input type='hidden' id='label-cama-opcion-seleccion".$opciones['id_opcion_seleccion']."' name='label-cama-opcion-seleccion[]' value=''>";
                                    
                                    
                                    
                                    
                                    if($tipo_pantalla == 3) {
                                        $opcion_seleccion.= "<div>";
                                    } else {
                                        $opcion_seleccion.= "<div class='col-lg-5'>";
                                    }

                                    switch ($tipo_seleccion) {
                                        case '1':
                                        case '3':
                                            if($tipo_seleccion == '3' && !empty($opciones['id_opcion_seleccion_referencia'])) continue;
                                            $cantidad_seleccion++;
                                            if(empty($cabecera_seleccion)) {
                                                if(empty($mostrar_detalle)) {
                                                    $opcion_seleccion.= "<select campana-opcion='".$opciones['id_campana_opcion']."' opcion-seleccion='".$opciones['id_opcion_seleccion']."' tipo-seleccion='".$tipo_seleccion."' id='opcion-seleccion".$opciones['id_opcion_seleccion']."' ";
                                                    if(!empty($opciones['id_opcion_seleccion_referencia'])) {
                                                        $opcion_seleccion.= " id-referencia='opcion-seleccion".$opciones['id_opcion_seleccion_referencia']."' disabled='disabled' ";
                                                    }
                                                    $opcion_seleccion.= "name='opcion-seleccion[]' class='form-control input-sm'>";

                                                    $key = array_search($opciones['id_opcion_seleccion'], array_column($data_s, 'id_opcion_seleccion'));
                                                    $contar_i=0;
                                                    for($i=$key;$i<count($data_s);$i++) { 
                                                        if($data_s[$i]['id_opcion_seleccion'] == $opciones['id_opcion_seleccion']) {
                                                            if($contar_i == 0 && $data_s[$i]['cantidad_seleccion'] == 1) {
                                                                $opcion_seleccion.= "<option value='-1'>Seleccionar</option>";
                                                            }
                                                            if(empty($opciones['id_opcion_seleccion_referencia'])) {
                                                                if($contar_i == 0 && $data_s[$i]['cantidad_seleccion'] == 0) {
                                                                    $opcion_seleccion.= "<option cantidad='0' value='0'>0</option>";
                                                                } else {
                                                                    $opcion_seleccion.= "<option keyseleccion='".$data_s[$i]['id_opcion_seleccion_detalle']."' cantidad='".$data_s[$i]['cantidad_seleccion']."' ";
                                                                    if( $tipo_seleccion == '3') {
                                                                        $opcion_seleccion.= "value='".$data_s[$i]['descripcion_detalle']."'>";
                                                                    } else {
                                                                        $opcion_seleccion.= "value='".$data_s[$i]['importe_seleccion']."'>";
                                                                    }

                                                                    if( $tipo_seleccion == '1') {

                                                                        if($utiliza_descripcion == '1') {
                                                                            $opcion_seleccion.= $data_s[$i]['cantidad_seleccion']." x ".$data_s[$i]['importe_seleccion'];
                                                                        } else {
                                                                            $opcion_seleccion.= $data_s[$i]['cantidad_seleccion']." ".$descripcion;
                                                                        }
                                                                    } else {
                                                                        $opcion_seleccion.= $data_s[$i]['descripcion_detalle'];
                                                                    }
                                                                    $opcion_seleccion.= "</option>";
                                                                }
                                                            }
                                                        } else {
                                                            continue;
                                                        }
                                                        $contar_i++;
                                                    }
                                                    $opcion_seleccion.= "</select>";
                                                } else {
                                                    $es_extendido = true;
                                                    $opcion_seleccion.= "<div campana-opcion='".$opciones['id_campana_opcion']."' opcion-seleccion='".$opciones['id_opcion_seleccion']."' tipo-seleccion='".$tipo_seleccion."' id='opcion-seleccion".$opciones['id_opcion_seleccion']."' ";
                                                    if(!empty($opciones['id_opcion_seleccion_referencia'])) {
                                                        $opcion_seleccion.= " id-referencia='opcion-seleccion".$opciones['id_opcion_seleccion_referencia']."' disabled='disabled' ";
                                                    }
                                                    $opcion_seleccion.= "name='opcion-seleccion[]' >";

                                                    $key = array_search($opciones['id_opcion_seleccion'], array_column($data_s, 'id_opcion_seleccion'));
                                                    $contar_i=0;
                                                    for($i=$key;$i<count($data_s);$i++) { 
                                                        if($data_s[$i]['id_opcion_seleccion'] == $opciones['id_opcion_seleccion']) {
                                                            if(empty($opciones['id_opcion_seleccion_referencia'])) {
                                                                    $opcion_seleccion.= "<div class='opcion-seleccion-detallado'><input type='radio' keyseleccion='".$data_s[$i]['id_opcion_seleccion_detalle']."' cantidad='".$data_s[$i]['cantidad_seleccion']."' ";
                                                                    $opcion_seleccion.= "value = '".$data_s[$i]['descripcion_detalle']."' ";
                                                                    $opcion_seleccion.= "id='opcion-seleccion".$data_s[$i]['id_opcion_seleccion']."' ";
                                                                    $opcion_seleccion.= "name='opcion-seleccion[]' ";
                                                                    $opcion_seleccion.= "campana-opcion='".$opciones['id_campana_opcion']."' ";
                                                                    $opcion_seleccion.= ">".$data_s[$i]['descripcion_detalle'];
                                                                    $opcion_seleccion.= "</input></div>";
                                                            }
                                                        } else {
                                                            continue;
                                                        }
                                                        $contar_i++;
                                                    }
                                                    $opcion_seleccion.= "</div>";
                                                }
                                            } else {
                                                $opcion_seleccion.= "<div class='opcion-seleccion-row'>";

                                                $key = array_search($opciones['id_opcion_seleccion'], array_column($data_s, 'id_opcion_seleccion'));
                                                $contar_i=0;
                                                for($i=$key;$i<count($data_s);$i++) { 
                                                    if($data_s[$i]['id_opcion_seleccion'] == $opciones['id_opcion_seleccion']) {
                                                        if(empty($opciones['id_opcion_seleccion_referencia'])) {
                                                                switch($data_s[$i]['tipo_seleccion_detalle']) {
                                                                    case 'A':
                                                                        $disabled = "";
                                                                        $total_adultos  = 1;
                                                                        $total_ninos    = 0;
                                                                        $total_infantes = 0;
                                                                        break;
                                                                    case 'N':
                                                                        $disabled = "disabled='disabled' ";
                                                                        $total_adultos  = 0;
                                                                        $total_ninos    = 1;
                                                                        $total_infantes = 0;
                                                                        break;
                                                                    case 'I':
                                                                        $disabled = "disabled='disabled' ";
                                                                        $total_adultos  = 0;
                                                                        $total_ninos    = 0;
                                                                        $total_infantes = 1;
                                                                        break;
                                                                    default:
                                                                        $disabled = "";
                                                                        $total_adultos  = 0;
                                                                        $total_ninos    = 0;
                                                                        $total_infantes = 0;
                                                                        break;
                                                                }
                                                            
                                                                $opcion_seleccion.= "<div><div>";
                                                                $opcion_seleccion.= "<input type='hidden' ";
                                                                $opcion_seleccion.= "id='opcion-seleccion".$data_s[$i]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                $opcion_seleccion.= "keyseleccion='".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                $opcion_seleccion.= "cantidad='".$data_s[$i]['cantidad_seleccion']."' ";
                                                                $opcion_seleccion.= "value='".$data_s[$i]['descripcion_detalle']."' >";
                                                                $opcion_seleccion.= "<div>".$data_s[$i]['descripcion_detalle']."</div>";
                                                                $opcion_seleccion.= "</div>";

                                                                $key_referencia_precio = array_search('4', array_column($data_o, 'tipo_seleccion'));
                                                                $opcion_seleccion.= "<div>";
                                                                $opcion_seleccion.= "<div id='precio-opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' class='opcion-venta-excursion precio-individual' >0.00</div>";
                                                                $opcion_seleccion.= "<input type='hidden' ";
                                                                $opcion_seleccion.= "campana-opcion='".$data_o[$key_referencia_precio]['id_campana_opcion']."' ";
                                                                $opcion_seleccion.= "opcion-seleccion='".$data_o[$key_referencia_precio]['id_opcion_seleccion']."' ";
                                                                $opcion_seleccion.= "tipo-seleccion='4' ";
                                                                $opcion_seleccion.= "id='opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                $opcion_seleccion.= "name='precio-opcion-seleccion[]' ";
                                                                $opcion_seleccion.= "id-referencia='opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion_referencia']."' ";
                                                                
                                                                $opcion_seleccion.= "id-referencia-doble='opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion_referencia_doble']."' ";
                                                                $opcion_seleccion.= "id-referencia-triple='opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion_referencia_triple']."' ";
                                                                $opcion_seleccion.= "padre-referencia='".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                $opcion_seleccion.= "value='0.00' ".$disabled."/></div>";
                                                                
                                                                $opcion_seleccion.= "<div>";
                                                                $key_referencia = array_search($data_s[$i]['id_opcion_seleccion_detalle'], array_column($data_s, 'id_detalle_referencia'));
                                                                if($key_referencia != null) {
                                                                    
                                                                    $opcion_seleccion.= "<input type='hidden' id='label-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='label-opcion-seleccion[]' value='<b>".$opciones['descripcion_primaria']."</b> ".$opciones['descripcion_secundaria']."' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='cantidad-opcion-seleccion[]' value='".$total_adultos."' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='keyseleccion-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='keyseleccion-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='total-adultos-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='total-adultos-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='total-ninos-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='total-ninos-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='total-infantes-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='total-infantes-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-ninos-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='cantidad-ninos-opcion-seleccion[]' value='".$total_ninos."' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='cantidad-infantes-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='cantidad-infantes-opcion-seleccion[]' value='".$total_infantes."' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='label-habitacion-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='label-habitacion-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    $opcion_seleccion.= "<input type='hidden' id='label-cama-opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' name='label-cama-opcion-seleccion[]' value='' ".$disabled.">";
                                                                    
                                                                    $opcion_seleccion.= "<select campana-opcion='".$opciones['id_campana_opcion']."' ";
                                                                    $opcion_seleccion.= "opcion-seleccion='".$data_s[$key_referencia]['id_opcion_seleccion']."' ";
                                                                    $opcion_seleccion.= "opcion-seleccion-padre='".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                    $opcion_seleccion.= "tipo-seleccion='".$tipo_seleccion."' ";
                                                                    $opcion_seleccion.= "opcion-habilitar='opcion-seleccion".$data_o[$key_referencia_precio]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                    if($data_s[$i]['tipo_seleccion_detalle'] != null) {
                                                                        $opcion_seleccion.= "tipo-seleccion-detalle='".$data_s[$i]['tipo_seleccion_detalle']."' ";
                                                                    }
                                                                    $opcion_seleccion.= "id='opcion-seleccion".$data_s[$key_referencia]['id_opcion_seleccion']."-".$data_s[$i]['id_opcion_seleccion_detalle']."' ";
                                                                    $opcion_seleccion.= "name='opcion-seleccion[]' class='form-control input-sm' ".$disabled.">";
                                                                    $opcion_seleccion.= "<option value='-1'>Seleccionar</option>";
                                                                    for($j=$key_referencia;$j<count($data_s);$j++) { 
                                                                        if($data_s[$j]['id_detalle_referencia'] == $data_s[$i]['id_opcion_seleccion_detalle']) {
                                                                            $opcion_seleccion.= "<option keyseleccion='".$data_s[$j]['id_opcion_seleccion_detalle']."' cantidad='".$data_s[$j]['cantidad_seleccion']."' ";
                                                                            if($data_s[$j]['cantidad_seleccion_ninos'] != null) {
                                                                                $opcion_seleccion.= "cantidad-ninos='".$data_s[$j]['cantidad_seleccion_ninos']."' ";
                                                                            }
                                                                            if($data_s[$j]['cantidad_seleccion_infantes'] != null) {
                                                                                $opcion_seleccion.= "cantidad-infantes='".$data_s[$j]['cantidad_seleccion_infantes']."' ";
                                                                            }
                                                                            if($data_s[$i]['descripcion_detalle'] != null) {
                                                                                $opcion_seleccion.= "tipo-habitacion='".$data_s[$i]['descripcion_detalle']."' ";
                                                                            }
                                                                            
                                                                            $opcion_seleccion.= "value='".$data_s[$j]['descripcion_detalle']."'>".$data_s[$j]['descripcion_detalle']."</option>";
                                                                        } else {
                                                                            continue;
                                                                        }
                                                                    }
                                                                    $opcion_seleccion.= "</select>";
                                                                    
                                                                }
                                                                
                                                                $opcion_seleccion.= "</div></div>";
                                                        }
                                                    } else {
                                                        continue;
                                                    }
                                                    $contar_i++;
                                                }

                                                $opcion_seleccion.= "</div>";
                                            }
                                            $opcion_seleccion.= "</div></div>";
                                            if($tipo_seleccion == '1') $opcion_seleccion_right.= $opcion_seleccion;
                                            else
                                                if($tipo_pantalla == 3) {
                                                    if(empty($cabecera_seleccion))  {
                                                        if($es_extendido) $opcion_seleccion_left.= $opcion_seleccion;
                                                        else $opcion_seleccion_top.= $opcion_seleccion;
                                                    } else {
                                                        $opcion_seleccion_right.= $opcion_seleccion;
                                                    }
                                                } else {
                                                    $opcion_seleccion_left.= $opcion_seleccion;
                                                }
                                            break;
                                        case '2':
                                            $opcion_seleccion.= "<div class='input-group date'>";
                                            $opcion_seleccion.= "<input campana-opcion='".$opciones['id_campana_opcion']."' opcion-seleccion='".$opciones['id_opcion_seleccion']."' tipo-seleccion='".$tipo_seleccion."' id='opcion-seleccion".$opciones['id_opcion_seleccion']."' fecha-bloqueo='".$opciones['fecha_bloqueo']."' name='opcion-seleccion[]' class='form-control input-sm' value=''>";
                                            $opcion_seleccion.= "<span class='input-group-addon' id='hora_inicio_addon'><span class='glyphicon glyphicon-calendar'></span></span>";
                                            $opcion_seleccion.= "</div>";
                                            $opcion_seleccion.= "</div></div>";
                                            if($tipo_pantalla == 3) {
                                                if(empty($cabecera_seleccion))  {
                                                    if($es_extendido) $opcion_seleccion_left.= $opcion_seleccion;
                                                    else $opcion_seleccion_top.= $opcion_seleccion;
                                                } else {
                                                    $opcion_seleccion_left.= $opcion_seleccion;
                                                }
                                            } else {
                                                $opcion_seleccion_left.= $opcion_seleccion;
                                            }
                                            break;
                                    }
                                   
                                }
                                
                                $id_opcion_anterior = $opciones['id_campana_opcion'];   
                         
                        }
                        if($tipo_pantalla == 3) {
                            $opcion_venta_total = $opcion_venta."<div class='opcion-venta-excursion grupo-paquete-top'>";
                            $opcion_venta_total.= $opcion_seleccion_top;
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-left'>";
                            $opcion_venta_total.= "<div class='opcion-seleccion-row titulo-left'>Estandar</div>";
                            $opcion_venta_total.= $opcion_seleccion_left;
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-right'>";
                            $opcion_venta_total.= $opcion_seleccion_right;
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-bottom'>";
                            $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-left'>";
                            $opcion_venta_total.= "<div class='opcion-seleccion-row pie-left'>Seleccionar Hotel prioridad</div>";
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= "<div class='opcion-venta-excursion grupo-paquete-right'>";
                            $opcion_venta_total.= "<div class='opcion-seleccion-row pie-right'>En caso de no contar con disponibilidad se acomodara al pax en similar o superior</div>";
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= "</div>";
                            $opcion_venta_total.= $opcion_venta_bottom;
                        } else {
                            $opcion_venta_total = $opcion_venta."<div class='opcion-venta-excursion grupo-seleccion-left'>".$opcion_seleccion_left."</div><div class='opcion-venta-excursion grupo-seleccion-right'>".$opcion_seleccion_right."</div>".$opcion_venta_bottom;
                        }
                        $venta_opciones[] = array('id'   => $id_opcion_anterior,
                                                  'form' => $opcion_venta_total);
                        
                        ?>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Nav tabs -->
    <?php if($tipo_pantalla == 1) { ?>
    <div class="contenedor-tabs" id="contenedor-tabs-detalle">
    <?php } else { ?>
    <div class="contenedor-tabs total excursion" id="contenedor-tabs-detalle">
    <?php } ?>
        <div>
            <ul>
                
                <?php if($tipo_pantalla == 1) { ?>
                <li><a href="javascript:;" class="reftab" data-tab="taboferta"><ta class="btn btn-rebueno"><i class="glyphicon glyphicon-thumbs-up"></i></ta>  Todo sobre la oferta</a></li>
                <li class="hidde"><a href="javascript:;" class="reftab" data-tab="tabsaber"><ta class="btn btn-rebueno"><i class="glyphicon glyphicon-eye-open"></i></ta>  Lo que debes saber</a></li>
                <?php } else { ?>
                <li><a href="javascript:;" class="reftab" data-tab="taboferta"><ex class="btn"><i class="glyphicon glyphicon-sunglasses"></i></ex>Descripción de la excursión</a></li>
                <li class="hidde"><a href="javascript:;" class="reftab" data-tab="tabsaber"><ex class="btn"><i class="glyphicon glyphicon-info-sign"></i></ex>Información importante</a></li>
                <?php } ?>
                
                <?php if($tipo_pantalla == 1) { ?>
                <li class="hidde"><a href="javascript:;" class="reftab" data-tab="tabempresa"><ta class="btn btn-rebueno"><i class="glyphicon glyphicon-home"></i></ta>  La Empresa</a></li>
                <?php } ?>
            </ul>
        </div>
        <!-- Tab panes -->
        <?php if($tipo_pantalla == 1) { ?>
        <div class="contenedor-tabs-panel inicio" id="taboferta" >
        <?php } else { ?>
        <div class="contenedor-tabs-panel inicio excursion" id="taboferta" >
        <?php } ?>
            <nosale>
            <?php echo $detalle['sobre_campana']; ?>
            </nosale>
        </div>
        <?php
            //Agregamos la opcines de venta
            if($tipo_pantalla != 1) {
                foreach($venta_opciones as $venta_opcion) {
                ?>
                <div>
                <form role="form" id="form-opcion-venta<?php echo $venta_opcion['id'];?>">
                    <?php echo $venta_opcion['form'];?>
                </form>
                </div>
                <?php
                }
            }
            
            if($tipo_pantalla == 1) { ?>
        <div class="contenedor-tabs-panel inicio" id="tabsaber">
        <?php } else { ?>
        <div class="contenedor-tabs-panel" id="tabsaber">
        <?php } ?>
        
            <ul>
                <?php if($tipo_pantalla == 1) { ?>
                <li><a href="javascript:;" class="reftab" data-tab="tabsaber"><ta class="btn btn-rebueno"><i class="glyphicon glyphicon-eye-open"></i></ta>  Lo que debes saber</a></li>
                <?php } else { ?>
                <li><a href="javascript:;" class="reftab" data-tab="tabsaber"><ex class="btn"><i class="glyphicon glyphicon-info-sign"></i></ex>Información importante</a></li>
                <?php } ?>
            </ul>
            <?php if($tipo_pantalla == 1) { ?>
            <nosale>
                <?php echo $detalle['observaciones']; ?>
            </nosale>
            <?php } ?>
        </div>
        <?php if($tipo_pantalla != '1') { ?>
        <div class="contenedor-informacion">
            <nosale>
                <?php echo $detalle['observaciones']; ?>
            </nosale>
        </div>
        <?php } ?>
        <?php if($tipo_pantalla == 1) { ?>
        <div class="contenedor-tabs-panel inicio cierre" id="tabempresa">
            <ul>
                <li><a href="javascript:;" class="reftab" data-tab="tabempresa"><ta class="btn btn-rebueno"><i class="glyphicon glyphicon-home"></i></ta>  La Empresa</a></li>
            </ul>
        <?php foreach ($data_e as $empresa) { ?>
            <h2><?php echo $empresa["nombre_comercial"]; ?></h2>
            <div class="contenedor-tabs-panel-descripcion"><p><?php echo $empresa["descripcion"]; ?></p></div>
            <div class="contenedor-tabs-panel-datos">
                <div><b>Dirección:</b></div>
                <div><?php echo $empresa["direccion_comercial"]; ?></div>
                <div><b>Sitio Web:</b></div>                               
                <div><a href="<?php echo $empresa["web_site"]; ?>" title="<?php echo $empresa["nombre_comercial"]; ?>" target="_blank"><?php echo $empresa["web_site"]; ?></a></div>
                <div><b>Horario:</b></div>           
                <div><?php echo $empresa["horario"]; ?></div>
            </div>
            <div class="contenedor-tabs-panel-mapa">   
                <?php if(!empty($empresa["ubicacion_gps"])) { ?>
                <img src="<?php echo $empresa["ubicacion_gps"]; ?>">
                <?php } ?>
            </div>    
            <?php } ?>
        </div>
        <?php } ?>
    </div>
    <?php
}

$anterior = '';
$ultimo   = 'uno';
$contador = 0;
foreach ($data_p as $dato) {
    if ($dato['mostrar'] == 0 ) continue;
    $contador++;
    if($contador > 3) {
        $contador = 1;
         ?>
        </div>
        <div class="campana-en-linea">
        <?php
    }
    switch($contador) {
        case 1: $position = ' left';
            break;
        case 2: $position = ' center';
            break;
        case 3: $position = ' right';
            break;
    }
    
    $ruta_imagen_pro = $directorio.$dato['id_campana'].$sep_path.'small2'.$sep_path.'image1.jpg';
    if (file_exists($ruta_imagen_pro)){
        ob_start();
        $resource_image = imagecreatefromjpeg($ruta_imagen_pro);
        imagejpeg($resource_image);
        $imagedata = ob_get_clean();
        $image = 'data:image/jpeg;base64,'.base64_encode($imagedata);
    } else {
        $image = '';
    }
                
    if ($dato['categoria'] != $anterior) {
        ?>
        <section id="<?php echo $dato['categoria']; ?>">
            <h2 class="box_center">Otras buenas ofertas del día</h2>
            <div class="box_center"><div>
                    <div class="campana-en-linea">
                    <?php
                }
                ?>
                <div class="campana-stilo-<?php echo $ultimo.$position;?>" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="../../campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="../../campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                            <span class=""></span>
                            <img  class="lazy campana-imgreferencia-<?php echo $ultimo;?>" data-original="<?php echo $image;?>" src="../../img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="campana-texto-descuento-<?php echo $ultimo;?>">-<?php echo $dato['descuento']; ?>%</span>
                            <?php if( $dato['maximo_cupones'] > 0 ) { 
                                    $quedan = $dato['maximo_cupones'] - $dato['vendidos'];
                                    if( $quedan <= 10 ) { 
                                        if( $quedan <= 0 ) { ?>
                                    <span class="campana-quedan-agotado-<?php echo $ultimo;?>">¡Agotado!</span>
                                        <?php } else { ?>
                                    <span class="campana-quedan-<?php echo $ultimo;?>">Sólo quedan<br><?php echo $quedan;?> ofertas</span>
                                        <?php }
                                    }
                                } ?>
                        </a>
                    </div>
                    <div class="campana-texto-detalle-<?php echo $ultimo;?>">
                        <a href="../../campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </div>
                    <div class="campana-tarifario-<?php echo $ultimo;?>">
                        <div class="campana-precio-regular"><div class="campana-precio-center"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></div></div>
                        <div class="campana-precio-oferta-<?php echo $ultimo;?>"><?php echo $moneda['simbolo'];?>&nbsp;<?php echo $dato['precio_especial']; ?></div>
                        <div class="campana-precio-boton"><a class="btn btn-ver-oferta-<?php echo $ultimo;?>" href="../../campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" title="Ver oferta">Ver oferta »</a></div>
                    </div>
                    <p class="campana-vendidos-<?php echo $ultimo;?>">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}
?>
</div>

<script type="text/javascript">
    $(function () {
        $("img.lazy").lazyload();
    });

    function verifyUser(email, name) {

        $.ajax({
            type: "POST",
            url: "/campana/cliente",
            data: {email: email, name: name, facebook: '1'},
            success: function (data) {
                var cliente = $.parseJSON(data);
                if (cliente[0]) {
                    if (cliente[0].validar == '1') {
                        postfunction('/campana', 'detalle', '<?php echo base64_encode($id); ?>');
                    }
                }
            }
        });

    }
    
    function aceptarArteCampana(contrato, campana) {

        $.ajax({
            type: "POST",
            url: "/dashboard/empresa/aceptar-arte",
            data: {contrato: contrato, campana: campana},
            success: function (data) {
                var actualizar = $.parseJSON(data);
                if (actualizar[0]) {
                    if (actualizar[0].respuesta == '1') {
                        alert('Felicidades su promocion se encuentra en el area de programación lista para ser publicada en los próximos dias.');
                    }
                }
            }
        });

    }

    //$('#tabcontainer').equalHeights();

</script>
<script language="JavaScript">
    TargetDate = "<?php echo $fecha_final;?>";
    BackColor = "white";
    ForeColor = "black";
    CountActive = true;
    CountStepper = -1;
    LeadingZero = true;
    DisplayFormat = "%%D%%d, %%H%%h, %%M%%m, %%S%%s.";
    FinishMessage = "Se acabo la oferta.";
</script>
<script language="JavaScript" src="../../js/countdown.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        var posicion_precio = $("#detalle_precio").offset().top;
        var altura_maximo = $("#contenedor-tabs-detalle").offset().top + $("#contenedor-tabs-detalle").height() - $("#detalle_precio").height() ;

        $(window).scroll(function () {
             var altura_pantalla = $(window).scrollTop();
             if (altura_pantalla >= posicion_precio - 200) {
                if ($(window).scrollTop() <= altura_maximo - 200) {
                    $("#detalle_precio").css("top", (altura_pantalla) + "px");
                } else {
                    $("#detalle_precio").css("top", (altura_maximo - 200) + "px");
                }
            } else {
                $("#detalle_precio").css("top","0px");
            }
        });

        $(".reftab").click(function () {
            var id = $(this).attr('data-tab');
            var scroll;
            scroll = $('#' + id ).offset().top - 200;
            $(window).scrollTop(scroll);
        });
        
        $("[tipo-seleccion]").change(function () {
            var tipo_selecion = $(this).attr('tipo-seleccion');
            var id_selecion = $(this).attr('id');
            var opcion_seleccion_attr = $(this).attr('opcion-seleccion');
            var id_opcion = $(this).attr('campana-opcion');
            var name_selecion_each;
            var total;
            var habilitar;
            var key_seleccion, opcion_seleccion, id_opcion_seleccion;
            
            habilitar = true;

            switch(tipo_selecion){
                case '1':
                    total = 0;
                    
                    $('[campana-opcion=' + id_opcion + ']').each(function (index, value) { 
                        name_selecion_each = $(this).attr('id');
                        if( $(this).attr('tipo-seleccion') == '1' ) {
                            if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) >= 0) {
                                total += parseFloat($("#" + name_selecion_each + " option:selected" ).val());
                            } else {
                                habilitar = false;
                            }
                        } else {
                            if( $(this).attr('tipo-seleccion') == '3' ) {
                                if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) > 0) {
                                    habilitar = false;
                                }
                            } else {
                                if($("#" + name_selecion_each).val() == ''){
                                    habilitar = false;
                                }
                            }
                        }
                        
                    });
                    $("#cantidad-" + id_selecion ).val($("#" + id_selecion + " option:selected" ).attr('cantidad'));
                    $("#keyseleccion-" + id_selecion ).val($("#" + id_selecion + " option:selected" ).attr('keyseleccion'));
                    $('#total-opcion' + id_opcion).val(total);
                    $('#btntotal-opcion' + id_opcion).html('<div style=\'font-size:13px\'>Precio</div>' + '$ ' + total.toFixed(2));
                    break;
                case '2':
                    $('[campana-opcion=' + id_opcion + ']').each(function (index, value) { 
                        name_selecion_each = $(this).attr('id');
                        if( $(this).attr('tipo-seleccion') == '1' ) {
                            if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) < 0) {
                                habilitar = false;
                            }
                        } else {
                            if($("#" + name_selecion_each).val() == ''){
                                habilitar = false;
                            }
                        }
                    });
                    if($("#" + id_selecion).val() == ''){
                        habilitar = false;
                    }
                    break;
                case '3':
                    var cantidad_object;
                    var tipo_seleccion_referencia, id_opcion_seleccion_attr;
                    var cantidad_personas, cantidad_ninos, cantidad_infantes;
                    cantidad_object = 0;
                    id_opcion_seleccion_attr = 'opcion-seleccion' + opcion_seleccion_attr;
                    key_seleccion = $("#" + id_selecion + " option:selected" ).attr('keyseleccion');
                    
                    if($('[id-referencia=' + id_selecion + ']').size() > 0 || $('[id-referencia-doble=' + id_opcion_seleccion_attr + ']').size() > 0 || $('[id-referencia-triple=' + id_opcion_seleccion_attr + ']').size() > 0) {
                        
                        $.blockUI({ 
                            message:'Estamos procesando su petición ...',
                            css: { 
                            border: 'none', 
                            padding: '15px', 
                            backgroundColor: '#000', 
                            '-webkit-border-radius': '10px', 
                            '-moz-border-radius': '10px', 
                            opacity: .5, 
                            color: '#fff' 
                            } });
                        
                        if($("#" + id_selecion).attr('tipo-seleccion-detalle')) {
                            if($("#" + id_selecion + " option:selected" ).attr('cantidad'))          cantidad_personas = $("#" + id_selecion + " option:selected" ).attr('cantidad'); 
                            else cantidad_personas = -1;
                            if($("#" + id_selecion + " option:selected" ).attr('cantidad-ninos'))    cantidad_ninos    = $("#" + id_selecion + " option:selected" ).attr('cantidad-ninos'); 
                            else cantidad_ninos    = -1
                            if($("#" + id_selecion + " option:selected" ).attr('cantidad-infantes')) cantidad_infantes = $("#" + id_selecion + " option:selected" ).attr('cantidad-infantes'); 
                            else cantidad_infantes = -1;
                        } else {
                            cantidad_personas = -1; 
                            cantidad_ninos    = -1; 
                            cantidad_infantes = -1; 
                        }
                        
                        $('[id-referencia=' + id_selecion + ']').each(function (index, value) { 
                            cantidad_object++;
                            opcion_seleccion = $(this).attr('opcion-seleccion');
                            id_opcion_seleccion = $(this).attr('id');
                            tipo_seleccion_referencia = $(this).attr('tipo-seleccion');
                            if(tipo_seleccion_referencia == '1') {
                                $(this).find('[keyseleccion]').remove();
                                $.ajax({
                                    type: "POST",
                                    url: "/campana/selecciondetallereferencia",
                                    data: {objeto:id_opcion_seleccion, id_opcion_seleccion: opcion_seleccion, id_referencia: key_seleccion},
                                    success: function (data) {
                                        var valores = $.parseJSON(data);
                                        if(valores.datos.length > 0) {
                                            for(var i=0;i<valores.datos.length;i++){
                                                $('#' + valores.name).append("<option keyseleccion='" + valores.datos[i].id_opcion_seleccion_detalle + "' cantidad='" + valores.datos[i].cantidad_seleccion + "' value='" + valores.datos[i].importe_seleccion + "'>" + valores.datos[i].cantidad_seleccion + ' x ' + valores.datos[i].importe_seleccion + "</option>");
                                            }
                                            $('#' + valores.name).removeAttr('disabled');
                                        } else {
                                            $('#' + valores.name).attr('disabled','disabled');
                                        }
                                        $('#cantidad-' + valores.name).val($("#" + valores.name + " option" ).first().attr('cantidad'));
                                        $('#keyseleccion-' + valores.name).val($("#" + valores.name + " option" ).first().attr('keyseleccion'));
                                        if($('[id-referencia=' + id_selecion + ']').size() == cantidad_object ) $.unblockUI();

                                    }
                                });
                                if( parseFloat($("#" + id_opcion_seleccion + " option:selected" ).val()) < 0) {
                                    habilitar = false;
                                }
                            } else {
                                
                                var id_referencia_doble = $(this).attr('id-referencia-doble');
                                var id_referencia_triple = $(this).attr('id-referencia-triple');
                                var key_padre = $(this).attr('padre-referencia');
                                var id_doble, id_triple, id_doble_sel, id_triple_sel;
                                
                                if($('#' + id_referencia_doble).length) id_doble = id_referencia_doble;
                                else id_doble = id_referencia_doble + '-' + key_padre;
                                
                                if( $('#' + id_doble).prop('tagName') == 'SELECT')  id_doble_sel = $("#" + id_doble + " option:selected").attr('keyseleccion') ? $("#" + id_doble + " option:selected").attr('keyseleccion') : $("#" + id_doble + " option:selected").val();
                                else id_doble_sel = $("#" + id_doble).attr('keyseleccion');
                                                                
                                if($('#' + id_referencia_triple).length) id_triple = id_referencia_triple;
                                else id_triple = id_referencia_triple + '-' +key_padre;
                                
                                if( $('#' + id_triple).prop('tagName') == 'SELECT')  id_triple_sel = $("#" + id_triple + " option:selected").attr('keyseleccion') ? $("#" + id_triple + " option:selected").attr('keyseleccion') : $("#" + id_triple + " option:selected").val();
                                else id_triple_sel = $("#" + id_triple).attr('keyseleccion');
                                
                                $.ajax({
                                    type: "POST",
                                    url: "/campana/selecciondetallereferencia",
                                    data: {objeto:id_opcion_seleccion, id_opcion_seleccion: opcion_seleccion, id_referencia: key_seleccion, id_referencia_doble: id_doble_sel, id_referencia_triple: id_triple_sel },
                                    success: function (data) {
                                        var valores = $.parseJSON(data);
                                        if(valores.datos.length > 0) {
                                            if(valores.datos.length == 1){
                                                $('#' + valores.name).val(valores.datos[0].importe_seleccion);
                                            } else {
                                                $('#' + valores.name).val('0.00');
                                            }
                                        } else {
                                            $('#' + valores.name).val('0.00');
                                        }
                                        if($('[id-referencia=' + id_selecion + ']').size() == cantidad_object ) $.unblockUI();
                                    }
                                });
                                
                                $('[campana-opcion=' + id_opcion + ']').each(function (index, value) { 
                                    name_selecion_each = $(this).attr('id');
                                    if( $(this).attr('tipo-seleccion') == '1' ) {
                                        if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) < 0) {
                                            habilitar = false;
                                        }
                                    } else {
                                        if($("#" + name_selecion_each).val() == ''){
                                            habilitar = false;
                                        }
                                    }
                                });
                            }
                        });
                        
                        $('[id-referencia-triple=' + id_opcion_seleccion_attr + ']').each(function (index, value) { 
                            var id_referencia_uno    = $(this).attr('id-referencia');
                            var id_referencia_doble  = $(this).attr('id-referencia-doble');
                            var id_referencia_triple  = $(this).attr('id-referencia-triple');
                            var key_padre = $(this).attr('padre-referencia');
                            var id_doble, id_uno, id_doble_sel, id_uno_sel,id_triple_sel, id_triple_sel;
                            var id_seleccion_key;
                            
                            cantidad_object++;
                            opcion_seleccion = $(this).attr('opcion-seleccion');
                            id_opcion_seleccion = $(this).attr('id');
                            tipo_seleccion_referencia = $(this).attr('tipo-seleccion');
                            
                            $('#label-' + id_referencia_doble).attr('disabled','disabled');
                            $('#cantidad-' + id_referencia_doble).attr('disabled','disabled');
                            $('#keyseleccion-' + id_referencia_doble).attr('disabled','disabled');
                            $('#precio-' + id_referencia_doble).attr('disabled','disabled');
                            
                            $('#total-adultos-' + id_referencia_doble).attr('disabled','disabled');
                            $('#total-ninos-' + id_referencia_doble).attr('disabled','disabled');
                            $('#total-infantes-' + id_referencia_doble).attr('disabled','disabled');
                            $('#cantidad-ninos-' + id_referencia_doble).attr('disabled','disabled');
                            $('#cantidad-infantes-' + id_referencia_doble).attr('disabled','disabled');
                            $('#label-habitacion-' + id_referencia_doble).attr('disabled','disabled');
                            $('#label-cama-' + id_referencia_doble).attr('disabled','disabled');
                            
                            if($('#' + id_referencia_uno).length) id_uno = id_referencia_uno;
                            else id_uno = id_referencia_uno + '-' +key_padre;

                            if($('#' + id_uno).prop('tagName') == 'SELECT')  id_uno_sel = $("#" + id_uno + " option:selected").attr('keyseleccion') ? $("#" + id_uno + " option:selected").attr('keyseleccion') : $("#" + id_uno + " option:selected").val();
                            else id_uno_sel = $("#" + id_uno).attr('keyseleccion');

                            if($('#' + id_referencia_doble).length) id_doble = id_referencia_doble;
                            else id_doble = id_referencia_doble + '-' + key_padre;

                            if($('#' + id_doble).prop('tagName') == 'SELECT')  id_doble_sel = $("#" + id_doble + " option:selected").attr('keyseleccion') ? $("#" + id_doble + " option:selected").attr('keyseleccion') : $("#" + id_doble + " option:selected").val();
                            else id_doble_sel = $("#" + id_doble).attr('keyseleccion');

                            if($('#' + id_referencia_triple).length) id_triple = id_referencia_triple;
                            else id_triple = id_referencia_triple + '-' + key_padre;

                            if($('#' + id_triple).prop('tagName') == 'SELECT')  id_triple_sel = $("#" + id_triple + " option:selected").attr('keyseleccion') ? $("#" + id_triple + " option:selected").attr('keyseleccion') : $("#" + id_triple + " option:selected").val();
                            else id_triple_sel = $("#" + id_triple).attr('keyseleccion');
                            
                            id_seleccion_key = id_referencia_triple + '-' + key_padre;
                            
                            $.ajax({
                                type: "POST",
                                url: "/campana/selecciondetallereferencia",
                                data: {objeto:id_opcion_seleccion, id_opcion_seleccion: opcion_seleccion, id_referencia: id_uno_sel, id_referencia_doble: id_doble_sel, id_referencia_triple: id_triple_sel, id_auxiliar_sel:id_selecion, id_auxiliar:id_seleccion_key },
                                success: function (data) {
                                    var valores = $.parseJSON(data);
                                    if(valores.nameauxiliarsel != valores.nameauxiliar) { 
                                        switch($('#' + valores.nameauxiliarsel).attr('tipo-seleccion-detalle')) {
                                            case 'A':
                                                if( $('#' + valores.nameauxiliar).attr('disabled') ) {
                                                    if( ( $('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad-ninos') > 0 && $('#' + valores.nameauxiliar).attr('tipo-seleccion-detalle') == 'N') || $('#' + valores.nameauxiliar).attr('tipo-seleccion-detalle') == 'I' ) {
                                                        $('#' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#label-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#cantidad-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#keyseleccion-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#total-adultos-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#total-ninos-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#total-infantes-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#cantidad-ninos-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#cantidad-infantes-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#label-habitacion-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#label-cama-' + valores.nameauxiliar).removeAttr('disabled');
                                                        $('#' + $('#' + valores.nameauxiliar).attr('opcion-habilitar')).removeAttr('disabled');
                                                    }
                                                } else {
                                                    $('#' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#label-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#cantidad-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#keyseleccion-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#total-adultos-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#total-ninos-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#total-infantes-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#cantidad-ninos-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#cantidad-infantes-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#label-habitacion-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#label-cama-' + valores.nameauxiliar).attr('disabled','disabled');
                                                    $('#' + $('#' + valores.nameauxiliar).attr('opcion-habilitar')).attr('disabled','disabled');
                                                }
                                                
                                                
                                                
                                                break;
                                            default:
                                                break;
                                        }
                                    } else {
                                        if( $('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad') ) $('#total-adultos-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad'));
                                        else $('#total-adultos-' + valores.nameauxiliarsel).val('');
                                        if( $('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad-ninos') ) $('#total-ninos-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad-ninos'));
                                        else $('#total-ninos-' + valores.nameauxiliarsel).val('');
                                        if( $('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad-infantes') ) $('#total-infantes-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").attr('cantidad-infantes'));
                                        else $('#total-infantes-' + valores.nameauxiliarsel).val('');
                                        if( $('#' + valores.nameauxiliarsel + " option:selected").attr('keyseleccion') ) $('#keyseleccion-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").attr('keyseleccion'));
                                        else $('#keyseleccion-' + valores.nameauxiliarsel).val('');
                                        if( $('#' + valores.nameauxiliarsel + " option:selected").attr('tipo-habitacion') ) $('#label-habitacion-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").attr('tipo-habitacion'));
                                        else $('#label-habitacion-' + valores.nameauxiliarsel).val('');
                                        $('#label-cama-' + valores.nameauxiliarsel).val($('#' + valores.nameauxiliarsel + " option:selected").html());
                                    }
                                    
                                    if(valores.datos.length > 0) {
                                        if(valores.datos.length == 1){
                                            $('#' + valores.name).val(valores.datos[0].importe_seleccion);
                                        } else {
                                            $('#' + valores.name).val('0.00');
                                        }
                                    } else {
                                        $('#' + valores.name).val('0.00');
                                    }
                                    $('#' + valores.name).trigger('change');
                                   if($('[id-referencia-triple=' + id_opcion_seleccion_attr + ']').size() == cantidad_object ) $.unblockUI();
                                }
                            });
                            
                            $('[campana-opcion=' + id_opcion + ']').each(function (index, value) { 
                                name_selecion_each = $(this).attr('id');
                                if( $(this).attr('tipo-seleccion') == '1' ) {
                                    if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) < 0) {
                                        habilitar = false;
                                    }
                                } else {
                                    if($("#" + name_selecion_each).val() == ''){
                                        habilitar = false;
                                    }
                                }
                            });
                        });
                    } else {
                        $('[campana-opcion=' + id_opcion + ']').each(function (index, value) { 
                            name_selecion_each = $(this).attr('id');
                            if( $(this).attr('tipo-seleccion') == '1' ) {
                                if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) < 0) {
                                    habilitar = false;
                                }
                            } else {
                                if($("#" + name_selecion_each).val() == ''){
                                    habilitar = false;
                                }
                            }
                        });
                    }
                    
                    break;
                case '4':
                    total = 0;
                    
                    $('[tipo-seleccion=4]').each(function (index, value) { 
                        name_selecion_each = $(this).attr('id');
                        //if( parseFloat($("#" + name_selecion_each + " option:selected" ).val()) >= 0) {
                            total += parseFloat($("#" + name_selecion_each).val());
                        //} else {
                        //    habilitar = false;
                        //}
                    });
                    $('#total-opcion' + id_opcion).val(total);
                    $('#btntotal-opcion' + id_opcion).html('<div style=\'font-size:13px\'>Precio</div>' + '$ ' + total.toFixed(2));
                    break;
            }
            if(habilitar) {
               $('#btncomprar-opcion' + id_opcion).removeAttr('disabled');
               $('#btncarrito-opcion' + id_opcion).removeAttr('disabled');
            } else {
               $('#btncomprar-opcion' + id_opcion).attr('disabled','disabled');
               $('#btncarrito-opcion' + id_opcion).attr('disabled','disabled');
            }
        });
        
        $("[boton-compra]").click(function () {
            var formulario_seleccion = $(this).attr('boton-compra');
            var disabled_seleccion = $(this).attr('disabled');
            
            if(!disabled_seleccion) {
                $('#'+formulario_seleccion).attr('method','post')
                $('#'+formulario_seleccion).attr('action','/campana/formulariopago')

                $("<input type='hidden'/>").attr("name", "op").attr("value", $(this).attr('campana-opcion')).prependTo('#'+formulario_seleccion);
                $("<input type='hidden'/>").attr("name", "id").attr("value", $(this).attr('campana')).prependTo('#'+formulario_seleccion);

                $('#'+formulario_seleccion).submit();
            }
        });
        
        $("[boton-carrito]").click(function () {
            var formulario_seleccion = $(this).attr('boton-carrito');
            var disabled_seleccion = $(this).attr('disabled');
            
            if(!disabled_seleccion) {
                
                $.blockUI({ 
                    message:'Agregando al carrito ...',
                    css: { 
                    border: 'none', 
                    padding: '15px', 
                    backgroundColor: '#000', 
                    '-webkit-border-radius': '10px', 
                    '-moz-border-radius': '10px', 
                    opacity: .5, 
                    color: '#fff' 
                } });
                
                $("<input type='hidden'/>").attr("name", "tp").attr("value", '<?php echo $tipo_pantalla;?>').prependTo('#'+formulario_seleccion);
                $("<input type='hidden'/>").attr("name", "op").attr("value", $(this).attr('campana-opcion')).prependTo('#'+formulario_seleccion);
                $("<input type='hidden'/>").attr("name", "id").attr("value", $(this).attr('campana')).prependTo('#'+formulario_seleccion);
                

                var dataString = $('#'+formulario_seleccion).serialize();

                $.ajax({
                    type: "POST",
                    url: "/campana/agregarcarrito",
                    data: dataString,
                    success: function (data) {
                        var valores = $.parseJSON(data);
                        var id_seleccion;
                        if(valores.respuesta.completo == 'N') {
                            $('[tipo-seleccion-detalle=A]').each(function (index, value) { 
                                id_seleccion = $(this).attr('id');
                                alert('es un A ' + id_seleccion);
                                if(valores.respuesta.activacion.A == 'N') {
                                    if(!$('#' + id_seleccion).attr('disabled')) {
                                        alert('desabilitar ' + id_seleccion);
                                        $('#' + id_seleccion).val('-1');
                                        $('#' + id_seleccion).attr('disabled','disabled');
                                        $('#label-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-' + id_seleccion).attr('disabled','disabled');
                                        $('#keyseleccion-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-adultos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-habitacion-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-cama-' + id_seleccion).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).val('0.00');
                                    }
                                } else {
                                    if(!$('#' + id_seleccion).attr('disabled')) {
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).val('0.00');
                                        $('#' + id_seleccion + ' option:not(:selected)').attr('disabled', true);
                                        $('#' + $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).attr('id-referencia')).val('-1');
                                        $('input[type="radio"]:not(:checked)').attr('disabled','disabled');
                                    }
                                }
                            });
                            $('[tipo-seleccion-detalle=N]').each(function (index, value) { 
                                id_seleccion = $(this).attr('id');
                                alert('es un N ' + id_seleccion);
                                if(valores.respuesta.activacion.N == 'N') {
                                    if(!$(this).attr('disabled')) {
                                        alert('desabilitar '+id_seleccion);
                                        $(this).val('-1');
                                        $('#' + id_seleccion).attr('disabled','disabled');
                                        $('#label-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-' + id_seleccion).attr('disabled','disabled');
                                        $('#keyseleccion-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-adultos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-habitacion-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-cama-' + id_seleccion).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).val('0.00');
                                    }
                                } else {
                                    //alert('activar '+ $(this).attr('disabled').length);
                                    if(!$(this).attr('disabled')) {
                                        alert('change '+id_seleccion);
                                        $(this).val('-1');
                                        $(this).trigger('change');
                                    }
                                }
                            });
                            $('[tipo-seleccion-detalle=I]').each(function (index, value) { 
                                id_seleccion = $(this).attr('id');
                                alert('es un I ' + id_seleccion);
                                if(valores.respuesta.activacion.I == 'N') {
                                    if(!$(this).attr('disabled')) {
                                        alert('desabilitar '+id_seleccion);
                                        $(this).val('-1');
                                        $('#' + id_seleccion).attr('disabled','disabled');
                                        $('#label-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-' + id_seleccion).attr('disabled','disabled');
                                        $('#keyseleccion-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-adultos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#total-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-ninos-' + id_seleccion).attr('disabled','disabled');
                                        $('#cantidad-infantes-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-habitacion-' + id_seleccion).attr('disabled','disabled');
                                        $('#label-cama-' + id_seleccion).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).attr('disabled','disabled');
                                        $('#' + $('#' + id_seleccion).attr('opcion-habilitar')).val('0.00');
                                    }
                                } else {
                                    if(!$(this).attr('disabled')) {
                                        $(this).val('-1');
                                        $(this).trigger('change');
                                        alert('change '+id_seleccion);
                                    }
                                }
                            });
                        } else {
                            $("#opcion-cantidad-carrito").html(valores.carrito.length);
                        }
                        $.unblockUI();
                    }
                });
            }
        });
        
        $('[tipo-seleccion=2]').each(function (index, value) { 
            $(this).datetimepicker({
                yearOffset:0,
                lang:'es',
                timepicker:false,
                format:'Y-m-d',
                formatDate:'Y/m/d',
                startDate:$(this).attr('fecha-bloqueo'),
                minDate:$(this).attr('fecha-bloqueo')
            });
        });
        
       
        
    });
</script>