<div class="contenedor-carrusel">
    <div  class="container total">
        <div id="slider-principal" class="carousel slide carrusel-principal" data-ride="carousel">
            <!-- Indicators -->
            <!--ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            </ol-->
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_1.jpg">
                    </div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <a href="/campana/categoria/MQ=="><div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_2.jpg">
                        </div></a>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <a href="/campana/categoria/MTU="><div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_3.jpg">
                    </div></a>
                    <div class="carousel-caption"></div>
                </div>
                <!--div class="item">
                    <div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_4.jpg">
                    </div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_5.jpg">
                    </div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider">
                        <img src="img/banner/bnr_bg_bsi_1_6.jpg">
                    </div>
                    <div class="carousel-caption"></div>
                </div-->
                <a class="left carousel-control" href="#slider-principal" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#slider-principal" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <!--div id="slider-secundario" class="carousel slide carrusel-secundario" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <div class="item derecha active">
                    <a href="/campana/categoria/Mg=="><div class="slider">
                        <img src="img/banner_derecha/bnr_bg_bsi_1_0.jpg">
                    </div></a>
                </div>
                <div class="item derecha">
                    <a href="/campana/categoria/Mg=="><div class="slider">
                        <img src="img/banner_derecha/bnr_bg_bsi_1_1.jpg">
                    </div></a>
                </div>
                <div class="item derecha">
                    <a href="/campana/categoria/Mg=="><div class="slider">
                        <img src="img/banner_derecha/bnr_bg_bsi_1_2.jpg">
                    </div></a>
                </div>
            </div>
        </div-->
    </div>
</div>
<div class="container">
<?php
$anterior = '';

function crearUrl($str_cadena) {
    $nueva_cadena = trim($str_cadena);
    $nueva_cadena = str_replace('-', ' ', $nueva_cadena);
    $nueva_cadena = str_replace(' ', '-', $nueva_cadena);
    $nueva_cadena = str_replace(chr(47), '-', $nueva_cadena);
    $nueva_cadena = str_replace(chr(63), '', $nueva_cadena);
    return $nueva_cadena;
}
$contador = 0;
$color_muestra = 0;
$solo_uno = true;
$ultimo   = 'uno';
foreach ($data as $dato) {
    if ($dato['mostrar'] == 0 ) continue;
    if ($dato['categoria'] != $anterior) {
        $color_muestra++;
        ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <?php if($portada[0]['opcion'] == '1') { ?>
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria" title="Ver Todos" >Ver Todos »</a></h2></div>
            <?php } else { ?>
            <div class="box_center"><h1><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria" title="Ver Todos" >Ver Todos »</a></h1></div>
            <?php } ?>
            <div class="box_center"><div>
                    <div class="campana-en-linea">
                    <?php
                }
                $contador++;
                if( $ultimo == 'uno' || $solo_uno ) {
                    if($contador > 3) {
                        $contador = 1;
                        //$ultimo = 'dos';
                        $ultimo = 'uno';
                        $position = ' left';
                        ?>
                        </div>
                        <div class="campana-en-linea">
                        <?php
                    } else {
                        switch($contador) {
                            case 1: $position = ' left';
                                break;
                            case 2: $position = ' center';
                                break;
                            case 3: $position = ' right';
                                break;
                        }
                    }
                } else {
                    if($contador > 2) {
                        $contador = 1;
                        $ultimo = 'uno';
                        $position = ' left';
                        ?>
                        </div>
                        <div class="campana-en-linea">
                        <?php
                    } else {
                        switch($contador) {
                            case 1: $position = ' left';
                                break;
                            case 2: $position = ' right';
                                break;
                        }
                    }
                }
                
                $ruta_imagen_pro = $directorio.$dato['id_campana'].$sep_path.'small2'.$sep_path.'image1.jpg';
                if (file_exists($ruta_imagen_pro)){
                    ob_start();
                    $resource_image = imagecreatefromjpeg($ruta_imagen_pro);
                    imagejpeg($resource_image);
                    $imagedata = ob_get_clean();
                    $image = 'data:image/jpeg;base64,'.base64_encode($imagedata);
                } else {
                    $image = '';
                }
                    
                ?>
                <div class="campana-stilo-<?php echo $ultimo.$position;?>" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                            <span class=""></span>
                            <img  class="lazy campana-imgreferencia-<?php echo $ultimo;?>" data-original="<?php echo $image;?>" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <?php if( $dato['descuento'] <= 20) { 
                                    if($portada[0]['opcion'] == '1') { ?>
                                        <span class="campana-texto-especial-<?php echo $ultimo;?>">Precio Especial</span>
                            <?php   } else { ?>
                                        <div class="campana-texto-descuento-circle-<?php echo $ultimo;?>">
                                            <div class="campana-texto-descuento-top-<?php echo $ultimo;?>"><div><span>Precio</span></div></div>
                                        <div class="campana-texto-descuento-bottom-<?php echo $ultimo;?> color-background-solid<?php echo $color_muestra;?>"><div><span>Especial</span></div></div>
                                        </div>
                            <?php   }
                                  } else { 
                                    if($portada[0]['opcion'] == '1') { ?>
                                        <span class="campana-texto-descuento-<?php echo $ultimo;?>">-<?php echo $dato['descuento']; ?>%</span>
                            <?php   } else { ?>
                                        <div class="campana-texto-descuento-circle-<?php echo $ultimo;?>">
                                        <div class="campana-texto-descuento-top-<?php echo $ultimo;?>"><div>-<?php echo $dato['descuento']; ?></div></div>
                                        <div class="campana-texto-descuento-bottom-<?php echo $ultimo;?> color-background-solid<?php echo $color_muestra;?>"><div>% Off</div></div>
                                        </div>
                                        
                            <?php   }
                                  } ?>
                                <?php if( $dato['maximo_cupones'] > 0 ) { 
                                    $quedan = $dato['maximo_cupones'] - $dato['vendidos'];
                                    if( $quedan <= 10 ) { 
                                        if( $quedan <= 0 ) { ?>
                                    <span class="campana-quedan-agotado-<?php echo $ultimo;?>">¡Agotado!</span>
                                        <?php } else { ?>
                                    <span class="campana-quedan-<?php echo $ultimo;?>">Sólo quedan<br><?php echo $quedan;?> ofertas</span>
                                        <?php }
                                    }
                                } ?>
                        </a>
                    </div>
                    <div class="campana-texto-detalle-<?php echo $ultimo;?>">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </div>
                    <div class="campana-tarifario-<?php echo $ultimo;?>">
                        <div class="campana-precio-regular">
                            <?php if($dato['id_tipo_pantalla'] == '2') { 
                                        $duracion = "";
                                        $duracion_venta = "";
                                        if(!empty($dato['duracion_dias'])) $duracion .= $dato['duracion_dias']." días ";
                                        if(!empty($dato['duracion_horas'])) $duracion .= $dato['duracion_horas']." horas";
                                        if(!empty($duracion)) {
                                            $duracion_venta = "<div class='campana-precio-center titulo-duracion-completa'><span class='glyphicon glyphicon-time'></span> ".$duracion."</div>";
                                        }
                                        echo $duracion_venta;
                                  } else { ?>
                            <div class="campana-precio-center"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></div>
                            <?php } ?>
                        </div>
                        <div class="campana-precio-oferta-<?php echo $ultimo;?> color-texto<?php echo $color_muestra;?>"><?php echo $moneda['simbolo'];?>&nbsp;<?php echo $dato['precio_especial']; ?></div>
                        <div class="campana-precio-boton"><a class="btn btn-ver-oferta-<?php echo $ultimo;?> color-background<?php echo $color_muestra;?>" href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" title="Ver oferta"><?php echo $portada[0]['boton-texto'];?> <?php if($portada[0]['opcion'] != '1') { ?><span class="glyphicon glyphicon-play"></span><?php } ?></a></div>
                    </div>
                    <?php if($portada[0]['opcion'] == '1') { ?>
                    <p class="campana-vendidos-<?php echo $ultimo;?>">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                    <?php } ?>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
                </div>
            </div> 
        </div>
    </section>
    <?php
}

$anterior = '';
foreach ($dataG as $dato) {
    if ($dato['mostrar'] == 0 ) continue;
    if ($dato['categoria'] != $anterior) {
        $color_muestra++;
        if($color_muestra > 2 ) $color_muestra = 1;
        $contador = 0;
        if( $ultimo == 'uno' ) {
            if($solo_uno) $ultimo = 'uno';
            else $ultimo = 'dos';
        } else {
            $ultimo = 'uno';
        }
        
        $position = ' left';
        
        if ($anterior != '') {
            ?>
            </div> 
            </div>
            </section>
        <?php } ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <?php if($portada[0]['opcion'] == '1') { ?>
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria/<?php echo base64_encode($dato['id_categoria']); ?>" title="Ver Todos" >Ver Todos »</a></h2></div>
            <?php } else { ?> 
            <div class="box_center"><h1><?php if(empty($dato['comentario'])) { echo $dato['categoria']; } else { echo $dato['comentario']; } ?> <span class='<?php echo $dato['icono']; ?>'></span></h1></div>
            <?php } ?>
            <div class="box_center"><div>
                    <div class="campana-en-linea">
                    <?php
                }
                $contador++;
                if( $ultimo == 'uno' || $solo_uno ) {
                    if($contador > 3) {
                        $contador = 1;
                        if($solo_uno) $ultimo = 'uno';
                        else $ultimo = 'dos';
                        $position = ' left';
                        ?>
                        </div>
                        <div class="campana-en-linea">
                        <?php
                    } else {
                        switch($contador) {
                            case 1: $position = ' left';
                                break;
                            case 2: $position = ' center';
                                break;
                            case 3: $position = ' right';
                                break;
                        }
                    }
                } else {
                    if($contador > 2) {
                        $contador = 1;
                        $ultimo = 'uno';
                        $position = ' left';
                        ?>
                        </div>
                        <div class="campana-en-linea">
                        <?php
                    } else {
                        switch($contador) {
                            case 1: $position = ' left';
                                break;
                            case 2: $position = ' right';
                                break;
                        }
                    }
                }
                
                $ruta_imagen_pro = $directorio.$dato['id_campana'].$sep_path.'small2'.$sep_path.'image1.jpg';
                if (file_exists($ruta_imagen_pro)){
                    ob_start();
                    $resource_image = imagecreatefromjpeg($ruta_imagen_pro);
                    imagejpeg($resource_image);
                    $imagedata = ob_get_clean();
                    $image = 'data:image/jpeg;base64,'.base64_encode($imagedata);
                } else {
                    $image = '';
                }
                
                ?>
                <div class="campana-stilo-<?php echo $ultimo.$position;?>" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                            <span class=""></span>
                            <img  class="lazy campana-imgreferencia-<?php echo $ultimo;?>" data-original="<?php echo $image;?>" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <?php if( $dato['descuento'] <= 20) { 
                                     if($portada[0]['opcion'] == '1') { ?>
                                        <span class="campana-texto-especial-<?php echo $ultimo;?>">Precio Especial</span>
                            <?php   } else { ?>
                                        <div class="campana-texto-descuento-circle-<?php echo $ultimo;?>">
                                            <div class="campana-texto-descuento-top-<?php echo $ultimo;?>"><div><span>Precio</span></div></div>
                                        <div class="campana-texto-descuento-bottom-<?php echo $ultimo;?> color-background-solid<?php echo $color_muestra;?>"><div><span>Especial</span></div></div>
                                        </div>
                            <?php   }
                                  } else { 
                                    if($portada[0]['opcion'] == '1') { ?>
                                        <span class="campana-texto-descuento-<?php echo $ultimo;?>">-<?php echo $dato['descuento']; ?>%</span>
                            <?php   } else { ?>
                                        <div class="campana-texto-descuento-circle-<?php echo $ultimo;?>">
                                        <div class="campana-texto-descuento-top-<?php echo $ultimo;?>"><div>-<?php echo $dato['descuento']; ?></div></div>
                                        <div class="campana-texto-descuento-bottom-<?php echo $ultimo;?> color-background-solid<?php echo $color_muestra;?>"><div>% Off</div></div>
                                        </div>
                                        
                            <?php   }
                                  } ?>
                                <?php if( $dato['maximo_cupones'] > 0 ) { 
                                    $quedan = $dato['maximo_cupones'] - $dato['vendidos'];
                                    if( $quedan <= 10 ) { 
                                        if( $quedan <= 0 ) { ?>
                                    <span class="campana-quedan-agotado-<?php echo $ultimo;?>">¡Agotado!</span>
                                        <?php } else { ?>
                                    <span class="campana-quedan-<?php echo $ultimo;?>">Sólo quedan<br><?php echo $quedan;?> ofertas</span>
                                        <?php }
                                    }
                                } ?>
                        </a>
                    </div>
                    <div class="campana-texto-detalle-<?php echo $ultimo;?>">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </div>
                    <div class="campana-tarifario-<?php echo $ultimo;?>">
                        <div class="campana-precio-regular"><div class="campana-precio-center"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></div></div>
                        <div class="campana-precio-oferta-<?php echo $ultimo;?> color-texto<?php echo $color_muestra;?>"><?php echo $moneda['simbolo'];?>&nbsp;<?php echo $dato['precio_especial']; ?></div>
                        <div class="campana-precio-boton"><a class="btn btn-ver-oferta-<?php echo $ultimo;?> color-background<?php echo $color_muestra;?>" href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" title="Ver oferta"><?php echo $portada[0]['boton-texto'];?> <?php if($portada[0]['opcion'] != '1') { ?><span class="glyphicon glyphicon-play"></span><?php } ?></a></div>
                    </div>
                    <?php if($portada[0]['opcion'] == '1') { ?>
                    <p class="campana-vendidos-<?php echo $ultimo;?>">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                    <?php } ?>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
                </div>
            </div> 
        </div>
    </section>
    <?php
}
?>
</div>            
<script type="text/javascript">
    $(function () {
        $("img.lazy").lazyload();
    });
</script>